### PR TITLE
Removed perftest, updated gitignore.

### PR DESCRIPTION
**Pull request by rk4n**

### CODE REVIEW

**Comment by vladiskuz** [comment]
What is the reason to add an empty directory and delete tests? Please add note to commit message.

**Comment by rk4n** [comment]
@vladiskuz test wasn't functional, perf test to compare two algorithms, nothing related to current codebase.
Empty dir is required by vagrant. 
```ruby
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.synced_folder "./shared_storage", "/var/lib/libvirt/images", type: "nfs"
```

**Comment by vladiskuz** [comment]
@rk4n please add the comment above to commit message. Thanks!

**Comment by rk4n** [comment]
@vladiskuz merge it plz if it's ok

**Pull request merged**
